### ISSUE TITLE
Pass URL from JSON Output

### ISSUE THREAD

**Issue by iappala** [ansu5555/pdf-viewer-reactjs#28] opened 2020-05-19 17:04 UTC
Hi,

I'm trying to pass URL from JSON output (using Fetch - ReactJS) and it's not rendering the PDF file (the same file works if I directly place the link in quotes)

Direct Input works:
<PDFViewer document={{ url: "TestDoc.pdf"}}/>

Doesn't work:
var link = this.state.docs.document_url;
 <PDFViewer document={{ url: link }}  />

Even with quotes escaping it doesn't work.
  var link = this.state.docs.document_url;
       link = "\""+link+ "\""
<PDFViewer document={{ url: link }}  />

Error in console:
Warning: Ignoring invalid character "33" in hex string
2pdf.worker.js:2023 Warning: Ignoring invalid character "45" in hex string
pdf.worker.js:2023 Warning: Ignoring invalid character "47" in hex string
pdf.worker.js:2023 Warning: Ignoring invalid character "42" in hex string
pdf.worker.js:2023 Warning: Ignoring invalid character "33" in hex string
57pdf.worker.js:2023 Warning: Ignoring invalid character "61" in hex 

Please help!!

**Comment by ansu5555** [comment] 2020-05-21 06:20
`this.state.docs.document_url` is blank or null so its giving the error message. Its the state nothing to do with the link.

**Comment by iappala** [comment] 2020-05-21 13:59
> `this.state.docs.document_url` is blank or null so its giving the error message. Its the state nothing to do with the link.

No it's not, I did resolve this issue with react-js but appreciate the help!

**Comment by ansu5555** [comment] 2020-05-21 15:39
Great, closing as the issue is resolved.

**Closed by ansu5555** 2020-05-21 15:39 UTC
