### ISSUE TITLE
Error while reading the pages

### ISSUE THREAD

**Issue by dominicpaul1911** [ansu5555/pdf-viewer-reactjs#51] opened 2020-11-12 04:18 UTC
**Describe the bug**
When clicking through the pdf pages (next and previous buttons) it sometimes shows an error 'Error while reading the pages'. 

Error in console shows 
----------------------
"Cannot update during an existing state transition (such as within `render`). Render methods should be a pure function of props and state."

**Expected behavior**
- When navigating PDF pages, should wait till it renders the next page OR
- Should have a prop type for 'Loading complete' which user can track and implement the logic accordingly

**Screenshots**
<img width="560" alt="Screenshot 2020-11-12 at 09 46 16" src="https://user-images.githubusercontent.com/5526167/98894940-eb535480-24cb-11eb-899a-23294c54def7.png">
<img width="1036" alt="Screenshot 2020-11-12 at 09 46 44" src="https://user-images.githubusercontent.com/5526167/98894971-fc03ca80-24cb-11eb-843d-7a1114c2be02.png">

**PDF File**
https://arxiv.org/pdf/quant-ph/0410100.pdf

**Details (please complete the following information):**
 - Device: Desktop
 - OS: OSX, Catalina
 - Browser Chrome, Brave

**Additional context**

**Comment by jay-patel-aubergine** [comment] 2020-12-31 05:10
I'm facing the same issue while loading any PDF file, is it fixed or have any workaround??

**Comment by anahernandez** [comment] 2021-01-29 13:44
The same problem appears to me if I move quickly between the pages of the PDF. If I go slow it loads well, but if I go fast it sometimes gives the same error. Any solution?

**Comment by ansu5555** [comment] 2021-01-30 10:54
> The same problem appears to me if I move quickly between the pages of the PDF. If I go slow it loads well, but if I go fast it sometimes gives the same error. Any solution?

thanks for the steps to reproduce the bug, will release the fix soon

**Comment by ansu5555** [comment] 2021-01-30 18:57
Fixed in v2.2.1

**Closed by ansu5555** 2021-01-30 18:57 UTC
Labels: bug

**Comment by jinfu868** [comment] 2021-05-06 10:32
I have latest 2.2.3, below code load thumbnails fine, but failed to display main page, error as : Error while reading the pages !
  <PDFViewer
      document={{
        url: "http://localhost:8080/api/getUserManual",
      }}      
 showThumbnail={{ scale: 3 }}
    />
  );

When check developer tools, I can see warning message below:

pdf-viewer-reactjs.js:1 Error while reading the pages !
 TypeError: Cannot read property 'getPage' of null
    at pdf-viewer-reactjs.js:1
    at tryCatch (runtime.js:63)
    at Generator.invoke [as _invoke] (runtime.js:293)
    at Generator.next (runtime.js:118)
    at asyncGeneratorStep (asyncToGenerator.js:3)
    at _next (asyncToGenerator.js:25)
    at asyncToGenerator.js:32
    at new Promise (<anonymous>)
    at asyncToGenerator.js:21
    at pdf-viewer-reactjs.js:1
    at pdf-viewer-reactjs.js:1
    at tryCatch (runtime.js:63)
    at Generator.invoke [as _invoke] (runtime.js:293)
    at Generator.next (runtime.js:118)
    at asyncGeneratorStep (asyncToGenerator.js:3)
    at _next (asyncToGenerator.js:25)
    at asyncToGenerator.js:32
    at new Promise (<anonymous>)
    at asyncToGenerator.js:21
    at pdf-viewer-reactjs.js:1
    at pdf-viewer-reactjs.js:1
    at commitHookEffectListMount (react-dom.development.js:19731)
    at commitPassiveHookEffects (react-dom.development.js:19769)
    at HTMLUnknownElement.callCallback (react-dom.development.js:188)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:237)
    at invokeGuardedCallback (react-dom.development.js:292)
    at flushPassiveEffectsImpl (react-dom.development.js:22853)
    at unstable_runWithPriority (scheduler.development.js:653)
    at runWithPriority$1 (react-dom.development.js:11039)
    at flushPassiveEffects (react-dom.development.js:22820)
    at performSyncWorkOnRoot (react-dom.development.js:21737)
    at react-dom.development.js:11089
    at unstable_runWithPriority (scheduler.development.js:653)
    at runWithPriority$1 (react-dom.development.js:11039)
    at flushSyncCallbackQueueImpl (react-dom.development.js:11084)
    at flushSyncCallbackQueue (react-dom.development.js:11072)
    at unbatchedUpdates (react-dom.development.js:21909)
    at legacyRenderSubtreeIntoContainer (react-dom.development.js:24757)
    at Object.render (react-dom.development.js:24840)
    at Module.<anonymous> (index.tsx:15)
    at Module../src/index.tsx (index.tsx:17)
    at __webpack_require__ (bootstrap:851)
    at fn (bootstrap:150)
    at Object.1 (unauthorised.tsx:4)
    at __webpack_require__ (bootstrap:851)
    at checkDeferredModules (bootstrap:45)
    at Array.webpackJsonpCallback [as push] (bootstrap:32)
    at main.chunk.js:1

**Comment by Luiscastor** [comment] 2021-11-29 02:18
I'm still getting the error using version 2.2.1 :(

**Comment by WalissonRodrigo** [comment] 2022-03-09 22:49
https://github.com/ansu5555/pdf-viewer-reactjs/issues/80#issuecomment-965606233
This solution works to me without downgrade in pdfjs-dist, but i'm install manualy pdfjs-dist@2.6.347 because pdf-viewer-reactjs on package.json line 63 include **^** in version and that force npm get last version this package and cause crashes if you send url directly without useMemo to generate object with url 

Change your code: 
```
<PDFViewer
  document={{
    url: "http://localhost:8080/api/getUserManual",
    }}
    showThumbnail={{ scale: 3 }}
/>
```
to
````
  const pdfUrl = useMemo(() => ({ url: "http://localhost:8080/api/getUserManual" }));
  <PDFViewer
    document={pdfUrl}
    showThumbnail={{ scale: 3 }}
  />
````

And your code works if you has the same problem i found.

**Comment by codemasterlike** [comment] 2022-11-06 14:27
Hi, 

When i tried to change to useMemo(), it shows empty (white page)


Appreciate if anyone can advise, thanks
